repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
    - id: flake8

-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.17
    hooks:
    - id: isort
      args: [--check-only, -rc, -vb]

# -   repo: local
#     hooks:
#     -   id: wily
#         name: wily
#         entry: wily diff
#         verbose: true
#         language: python
#         additional_dependencies: [wily]
